<a href="https://colab.research.google.com/github/tkhasimbasha/python_ai/blob/master/Module_2/Module_2_Numpy_Basics_Hands_on.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Basics Hands-on

This notebook illustrates various NumPy functions, showing how to create and manipulate arrays, perform vectorized arithmetic, utilize statistical methods, handle broadcasting, and make use of NumPy’s linear algebra and random modules.

In [ ]:
# ---------------------------------------------------------------------
# 1. IMPORTS AND BASIC SETUP
# ---------------------------------------------------------------------
import numpy as np

# For reproducibility in examples that use random numbers
rng = np.random.default_rng(seed=42)

print("NumPy version:", np.__version__)

NumPy version: 1.26.4


## 2. Array Creation

NumPy provides multiple ways to create arrays:
- **np.array()**: Convert a Python list or tuple to a NumPy array
- **np.zeros()**: Create an array of all zeros
- **np.ones()**: Create an array of all ones
- **np.arange()**: Create an array with a range of integers
- **np.linspace()**: Create an array of evenly spaced numbers

In [ ]:
# ---------------------------------------------------------------------
# 2. ARRAY CREATION EXAMPLES
# ---------------------------------------------------------------------

# 2.1 Creating an array from a Python list
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print("Array from list:", arr_from_list)

Array from list: [1 2 3 4 5]


In [ ]:
type(arr_from_list)

numpy.ndarray

In [ ]:
# 2.2 Creating an array of zeros
arr_zeros = np.zeros((2, 3))  # 2x3 matrix of zeros
print("\nArray of zeros:\n", arr_zeros)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 2.3 Creating an array of ones
arr_ones = np.ones((2, 3))    # 2x3 matrix of ones
print("\nArray of ones:\n", arr_ones)


Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr_ones.shape

(2, 3)

In [ ]:
arr_ones.ndim

2

In [ ]:
# 2.4 Creating an array with arange
arr_arange = np.arange(5, 15, 2)  # start=5, stop=15, step=2
print("\nArray with arange (5 to <15 step 2):", arr_arange)


Array with arange (5 to <15 step 2): [ 5  7  9 11 13]


In [ ]:
# 2.5 Creating an array with linspace
arr_linspace = np.linspace(0, 1, 5)  # 5 points from 0 to 1 inclusive
print("\nArray with linspace (0 to 1 in 5 steps):", arr_linspace)


Array with linspace (0 to 1 in 5 steps): [0.   0.25 0.5  0.75 1.  ]


## 3. Indexing and Slicing

Indexing and slicing let you access and modify parts of a NumPy array.  
- **1D arrays** work similarly to Python lists.  
- **Multi-dimensional arrays** require specifying the indices of each dimension.

Examples below cover basic slicing, stepping, advanced (fancy) indexing, and boolean indexing.

In [ ]:
# ---------------------------------------------------------------------
# 3. INDEXING AND SLICING EXAMPLES
# ---------------------------------------------------------------------

# 3.1 BASIC INDEXING
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D array:", arr_1d)
print("Element at index 2:", arr_1d[2])  # 0-based indexing

1D array: [10 20 30 40 50]
Element at index 2: 30


In [ ]:
# 3.2 SLICING
# Syntax: arr[start : stop : step]
# By default, start=0, stop=length of array, step=1

slice_1d = arr_1d[1:4]  # elements at indices 1, 2, 3
print("\nSliced 1D array (indices 1 to 3):", slice_1d)


Sliced 1D array (indices 1 to 3): [20 30 40]


In [ ]:
# 3.3 SLICING WITH STEPS
slice_step = arr_1d[::2]  # every 2nd element
print("Slicing with step of 2:", slice_step)

Slicing with step of 2: [10 30 50]


In [ ]:
# 3.4 MULTI-DIMENSIONAL SLICING
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n2D array:\n")
arr_2d


2D array:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Access the element in row=1, col=2
# (Remember, rows and cols are 0-indexed)
print("Element at [1, 2] (2D indexing):", arr_2d[1, 2])

Element at [1, 2] (2D indexing): 6


In [ ]:
# Slice rows from 0 to 1 and columns from 1 to 2
print("Slice rows 0:2, cols 1:3:\n", arr_2d[0:2, 1:3])

Slice rows 0:2, cols 1:3:
 [[2 3]
 [5 6]]


In [ ]:
# 3.5 FANCY (ADVANCED) INDEXING
# Use lists or arrays of indices to grab specific elements
indices = [2, 0]  # let's grab rows at indices 0 and 2
arr_fancy = arr_2d[indices, :]
print("\nFancy indexing (select rows [0, 2]):\n", arr_fancy)


Fancy indexing (select rows [0, 2]):
 [[7 8 9]
 [1 2 3]]


In [ ]:
# 3.6 BOOLEAN INDEXING
# Select elements satisfying a certain condition
bool_mask = arr_2d > 4
print("\nBoolean mask for arr_2d > 4:\n", bool_mask)
print("Elements > 4:", arr_2d[bool_mask])


Boolean mask for arr_2d > 4:
 [[False False False]
 [False  True  True]
 [ True  True  True]]
Elements > 4: [5 6 7 8 9]


In [ ]:
# We can combine boolean conditions using logical operators
bool_mask_combined = (arr_2d > 2) & (arr_2d < 8)
print("\nBoolean mask for arr_2d > 2 and arr_2d < 8:\n", bool_mask_combined)
print("Elements matching this condition:", arr_2d[bool_mask_combined])


Boolean mask for arr_2d > 2 and arr_2d < 8:
 [[False False  True]
 [ True  True  True]
 [ True False False]]
Elements matching this condition: [3 4 5 6 7]


## 4. Shape Manipulation

- **reshape()**: Returns a new view of the array with a different shape (the original array remains unchanged).
- **ravel()**: Flattens the array into 1D without creating a copy if possible.
- **transpose()**: Transposes the axes of the array.

In [ ]:
# ---------------------------------------------------------------------
# 4. SHAPE MANIPULATION EXAMPLES
# ---------------------------------------------------------------------

# Create a 2D array for demonstrations
matrix = np.arange(1, 13)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
matrix = matrix.reshape(3, 4)  # 3 rows, 4 columns
print("Original matrix:\n")
matrix

Original matrix:



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 4.1 Reshape
reshaped = matrix.reshape(2, 6)
print("\nReshaped to 2x6:\n", reshaped)


Reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# 4.2 Ravel
raveled = matrix.ravel()  # Flatten to 1D
print("\nRaveled (flattened):", raveled)


Raveled (flattened): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 4.3 Transpose
transposed = matrix.transpose()  # or matrix.T
print("\nTransposed matrix:\n")
transposed


Transposed matrix:



array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 5. Data Types

Every NumPy array has a single data type (dtype). You can:
- Check the data type via **array.dtype**
- Convert data types using **array.astype(...)**

In [ ]:
# ---------------------------------------------------------------------
# 5. DATA TYPE EXAMPLES
# ---------------------------------------------------------------------

arr_float = np.array([1.2, 3.14, 5.6])
print("Array:", arr_float)
print("Data type of arr_float:", arr_float.dtype)

Array: [1.2  3.14 5.6 ]
Data type of arr_float: float64


In [ ]:
arr_int = arr_float.astype(np.int64)
print("\nConverted to integer type:", arr_int)
print("Data type of arr_int:", arr_int.dtype)


Converted to integer type: [1 3 5]
Data type of arr_int: int64


## 6. Arithmetic Universal Functions

NumPy provides a wide range of “ufuncs” (universal functions) that apply element-wise:
- **np.add**, **np.subtract**, **np.multiply**, **np.divide**
- **np.log**, **np.log2**, **np.log10**
- **np.power**
- **np.exp**

In [ ]:
# ---------------------------------------------------------------------
# 6. ARITHMETIC UFUNCS
# ---------------------------------------------------------------------

x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

In [ ]:
# Basic arithmetic
print("Add:", np.add(x, y))
print("Subtract:", np.subtract(x, y))
print("Multiply:", np.multiply(x, y))
print("Divide:", np.divide(x, y))

Add: [11 22 33 44]
Subtract: [ -9 -18 -27 -36]
Multiply: [ 10  40  90 160]
Divide: [0.1 0.1 0.1 0.1]


In [ ]:
x/y

array([0.1, 0.1, 0.1, 0.1])

In [ ]:
# Logarithms (element-wise)
arr_for_log = np.array([1, np.e, 100])
arr_for_log

array([  1.        ,   2.71828183, 100.        ])

In [ ]:
np.log(arr_for_log)

array([0.        , 1.        , 4.60517019])

In [ ]:
np.log2(arr_for_log)

array([0.        , 1.44269504, 6.64385619])

In [ ]:
np.log10(arr_for_log)

array([0.        , 0.43429448, 2.        ])

In [ ]:
np.e, np.exp(1)

(2.718281828459045, 2.718281828459045)

In [ ]:
# Exponent and Power
arr_power = np.array([2, 3, 4])
print("\nOriginal numbers:", arr_power)
print("Squared (np.power):", np.power(arr_power, 2))
print("Exponent (np.exp):", np.exp(arr_power))


Original numbers: [2 3 4]
Squared (np.power): [ 4  9 16]
Exponent (np.exp): [ 7.3890561  20.08553692 54.59815003]


## 7. Trigonometric & Hyperbolic Functions

- **np.sin**, **np.cos**, **np.tan**
- **np.arcsin**, **np.arccos**, **np.arctan**
- **np.sinh**, **np.cosh**, **np.tanh**
- **np.arcsinh**, **np.arccosh**, **np.arctanh**

In [ ]:
# ---------------------------------------------------------------------
# 7. TRIGONOMETRIC & HYPERBOLIC UFUNCS
# ---------------------------------------------------------------------

angles = np.array([0, np.pi/2, np.pi])

print("Sin:", np.sin(angles))
print("Cos:", np.cos(angles))
print("Tan:", np.tan(angles))

Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
# Hyperbolic
values = np.array([-1, 0, 1])
print("\nSinh:", np.sinh(values))
print("Cosh:", np.cosh(values))
print("Tanh:", np.tanh(values))


Sinh: [-1.17520119  0.          1.17520119]
Cosh: [1.54308063 1.         1.54308063]
Tanh: [-0.76159416  0.          0.76159416]


## 8. Rounding & Other Element-wise Numeric UFuncs

- **np.abs(x)**: Absolute value
- **np.sign(x)**: Sign of the number (−1, 0, or 1)
- **np.round(x)**, **np.floor(x)**, **np.ceil(x)**, **np.trunc(x)**: Rounding operations

In [ ]:
# ---------------------------------------------------------------------
# 8. ROUNDING & OTHER ELEMENT-WISE UFUNCS
# ---------------------------------------------------------------------

data_values = np.array([-1.75, -0.22, 0.58, 1.91, 2.57])

print("Absolute:", np.abs(data_values))
print("Sign:", np.sign(data_values))

Absolute: [1.75 0.22 0.58 1.91 2.57]
Sign: [-1. -1.  1.  1.  1.]


In [ ]:
print("\nRound:", np.round(data_values))
print("Floor:", np.floor(data_values))
print("Ceil:", np.ceil(data_values))
print("Trunc:", np.trunc(data_values))


Round: [-2. -0.  1.  2.  3.]
Floor: [-2. -1.  0.  1.  2.]
Ceil: [-1. -0.  1.  2.  3.]
Trunc: [-1. -0.  0.  1.  2.]


## 9. Comparison and Logical UFuncs

- **np.less**, **np.less_equal**, **np.greater**, **np.greater_equal**, **np.equal**, **np.not_equal**
- **np.logical_and**, **np.logical_or**, **np.logical_xor**

In [ ]:
# ---------------------------------------------------------------------
# 9. COMPARISON & LOGICAL UFUNCS
# ---------------------------------------------------------------------

a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 2, 2])

print("np.less(a, b):", np.less(a, b))
print("np.greater_equal(a, b):", np.greater_equal(a, b))
print("np.equal(a, b):", np.equal(a, b))
print("np.not_equal(a, b):", np.not_equal(a, b))

np.less(a, b): [ True False False False]
np.greater_equal(a, b): [False  True  True  True]
np.equal(a, b): [False  True False False]
np.not_equal(a, b): [ True False  True  True]


In [ ]:
a >= b

array([False,  True,  True,  True])

In [ ]:
# Logical operations
cond1 = a > 1
cond2 = a < 4

print("\ncond1 (a > 1):", cond1)
print("cond2 (a < 4):", cond2)
print("logical_and(cond1, cond2):", np.logical_and(cond1, cond2))


cond1 (a > 1): [False  True  True  True]
cond2 (a < 4): [ True  True  True False]
logical_and(cond1, cond2): [False  True  True False]


## 10. Statistical & Aggregation Functions

- **np.sum**, **np.mean**, **np.std**, **np.var**
- **np.min**, **np.max**, **np.argmin**, **np.argmax**
- **np.median**, **np.quantile**

You can also specify an `axis` to perform these operations row-wise or column-wise on multi-dimensional arrays.

In [ ]:
# ---------------------------------------------------------------------
# 10. STATISTICAL & AGGREGATION FUNCTIONS
# ---------------------------------------------------------------------

stats_arr = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

print("Array:\n", stats_arr)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("\nSum of all elements:", np.sum(stats_arr))
print("Mean:", np.mean(stats_arr))
print("Standard Deviation:", np.std(stats_arr))
print("Variance:", np.var(stats_arr))


Sum of all elements: 45
Mean: 5.0
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667


In [ ]:
print("\nMin:", np.min(stats_arr))
print("Max:", np.max(stats_arr))
print("Argmin (index of min):", np.argmin(stats_arr))
print("Argmax (index of max):", np.argmax(stats_arr))


Min: 1
Max: 9
Argmin (index of min): 0
Argmax (index of max): 8


In [ ]:
print("\nMedian:", np.median(stats_arr))
print("Quantile (0.25):", np.quantile(stats_arr, 0.25))


Median: 5.0
Quantile (0.25): 3.0


In [ ]:
# Using axis parameter: sum along rows (axis=1) or columns (axis=0)
print("\nSum along rows:", np.sum(stats_arr, axis=1))
print("Sum along columns:", np.sum(stats_arr, axis=0))


Sum along rows: [ 6 15 24]
Sum along columns: [12 15 18]


## 11. Broadcasting

Broadcasting enables arithmetic between arrays of different shapes,
following certain rules. If the smaller array can be “stretched” to match
the larger array, NumPy performs the operation element-wise.

In [ ]:
# ---------------------------------------------------------------------
# 11. BROADCASTING EXAMPLES
# ---------------------------------------------------------------------

# Example 1: Adding a scalar to an array
arr_b = np.array([1, 2, 3])
print("Original array:", arr_b)
print("Add 10 to each element:", arr_b + 10)

Original array: [1 2 3]
Add 10 to each element: [11 12 13]


In [ ]:
# Example 2: Broadcasting two arrays of compatible shapes
mat_b1 = np.array([[1], [2], [3]])  # shape (3,1)
mat_b2 = np.array([10, 20, 30])     # shape (3,)

print("\nBroadcasting shapes (3,1) and (3,) in an operation:")
print("mat_b1 + mat_b2:\n", mat_b1 + mat_b2)


Broadcasting shapes (3,1) and (3,) in an operation:
mat_b1 + mat_b2:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## 12. Linear Algebra with `numpy.linalg`

Key functionalities include:
- **np.dot**, **np.matmul**, or the `@` operator for matrix multiplication
- **np.linalg.solve(A, b)** to solve a linear system
- **np.linalg.inv(A)** and **np.linalg.det(A)** for matrix inversion and determinant
- **np.linalg.eig(A)** for eigenvalues and eigenvectors
- **np.linalg.svd(A)** for singular value decomposition
- **np.linalg.norm(A)** for matrix/vector norms

In [ ]:
# ---------------------------------------------------------------------
# 12. LINEAR ALGEBRA EXAMPLES
# ---------------------------------------------------------------------

# Create a 2D matrix
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

In [ ]:
# 12.1 Matrix multiplication
print("A:\n", A)
print("B:\n", B)

print("\nMatrix multiplication (A @ B):\n", A @ B)
# or np.matmul(A, B) or np.dot(A, B)

A:
 [[1 2]
 [3 4]]
B:
 [[2 0]
 [1 2]]

Matrix multiplication (A @ B):
 [[ 4  4]
 [10  8]]


In [ ]:
B @ A

array([[ 2,  4],
       [ 7, 10]])

In [ ]:
A.dot(B)

array([[ 4,  4],
       [10,  8]])

In [ ]:
np.matmul(A,B)

array([[ 4,  4],
       [10,  8]])

In [ ]:
# 12.2 Matrix inversion & determinant
inv_A = np.linalg.inv(A)
det_A = np.linalg.det(A)

print("\nInverse of A:\n", inv_A)
print("Determinant of A:", det_A)


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004


## 13. NumPy Random Module

- **rng.integers()**, **rng.random()**, **rng.normal()**: Random sampling from different distributions
- **rng.shuffle()**, **rng.permutation()**: Shuffle or permute sequences
- **np.random.default_rng(seed)**: For a reproducible random number generator

In [ ]:
# ---------------------------------------------------------------------
# 13. RANDOM MODULE EXAMPLES
# ---------------------------------------------------------------------

# 13.1 Random Integers
rand_ints = rng.integers(low=0, high=10, size=5)
print("Random integers between 0 and 10:", rand_ints)

Random integers between 0 and 10: [0 7 6 4 4]


In [ ]:
# 13.2 Random floats in [0,1)
rand_floats = rng.random(5).round(2)
print("\nRandom floats in [0,1):", rand_floats)


Random floats in [0,1): [0.13 0.45 0.37 0.93 0.64]


In [ ]:
# 13.3 Normally distributed samples (mean=0, std=1)
rand_norm = rng.normal(loc=0, scale=1, size=5)
print("\nRandom normal distribution (mean=0, std=1):", rand_norm)


Random normal distribution (mean=0, std=1): [ 1.12724121  0.46750934 -0.85929246  0.36875078 -0.9588826 ]


In [ ]:
# 13.4 Shuffle and permutation
arr_shuf = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr_shuf)  # Shuffle in-place
print("\nShuffled array:", arr_shuf)


Shuffled array: [2 4 1 5 3]


In [ ]:
arr_perm = np.array([10, 20, 30, 40, 50])
print("Permutation of [10,20,30,40,50]:", rng.permutation(arr_perm))

Permutation of [10,20,30,40,50]: [50 40 30 20 10]


# Conclusion

We have demonstrated various NumPy capabilities including:
- Array creation
- Indexing and slicing
- Shape manipulation
- Arithmetic, logarithmic, and trigonometric functions
- Rounding, comparison, and logical operations
- Statistical and aggregation functions
- Broadcasting rules
- Linear algebra
- Random sampling